spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/smartcampus
    username: smartcampus
    password: smartcampus
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
