package com.sliitreserve.api.entities.analytics;

import com.sliitreserve.api.entities.facility.Facility;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Utilization Snapshot Entity - Daily facility utilization analytics record.
 *
 * Purpose: Stores calculated daily utilization metrics per facility for admin analytics.
 * Generated by nightly job that runs after each calendar day.
 *
 * Calculation (from FR-036, FR-037, FR-038):
 * - Available Hours: Hours facility is open in the day (excludable: maintenance, out_of_service)
 * - Booked Hours: Sum of confirmed booking durations for the day
 * - Utilization %: (bookedHours / availableHours) * 100
 * - Underutilized: Average% < 30% over trailing 30-day window
 * - Persistent: Flagged if underutilized for > 7 consecutive days
 *
 * Exclusions (from FR-036):
 * - Facilities under maintenance (status = OUT_OF_SERVICE)
 * - Facilities < 50 available hours in analysis window
 *
 * Lifecycle:
 * - Created: Nightly by UtilizationSnapshotService at 23:59 UTC
 * - Updated: Never (immutable once created)
 * - Queried: Admin analytics dashboard, underutilization detection
 * - Purged: Optional retention policy (e.g., keep 90 days)
 *
 * Relationships:
 * - Many-to-one Facility
 * - May reference RecommendationRecord for alternative facility suggestions
 */
@Entity
@Table(
    name = "utilization_snapshots",
    indexes = {
        @Index(columnList = "facility_id, snapshot_date DESC", name = "idx_utilization_facility_date"),
        @Index(columnList = "snapshot_date DESC", name = "idx_utilization_date"),
        @Index(columnList = "underutilized, snapshot_date DESC", name = "idx_utilization_underutilized")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UtilizationSnapshot {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "facility_id", nullable = false)
    private Facility facility;

    @Column(name = "snapshot_date", nullable = false)
    private LocalDate snapshotDate;

    @Column(name = "available_hours", nullable = false, precision = 10, scale = 2)
    private BigDecimal availableHours;

    @Column(name = "booked_hours", nullable = false, precision = 10, scale = 2)
    private BigDecimal bookedHours;

    @Column(name = "utilization_percent", nullable = false, precision = 5, scale = 2)
    private BigDecimal utilizationPercent;

    @Column(name = "underutilized", nullable = false)
    private Boolean underutilized;

    @Column(name = "consecutive_underutilized_days")
    private Integer consecutiveUnderutilizedDays;

    /**
     * Calculate utilization percentage.
     *
     * Formula: (bookedHours / availableHours) * 100
     * Special case: If availableHours is 0, returns 0%
     *
     * @return Calculated utilization percentage (0-100+)
     */
    public BigDecimal calculateUtilizationPercent() {
        if (availableHours == null || availableHours.compareTo(BigDecimal.ZERO) <= 0) {
            return BigDecimal.ZERO;
        }
        return bookedHours
            .divide(availableHours, 2, java.math.RoundingMode.HALF_UP)
            .multiply(new BigDecimal(100));
    }

    /**
     * Check if facility is underutilized (< 30% average over 30 days).
     *
     * @return true if underutilized, false otherwise
     */
    public boolean isUnderutilized() {
        return underutilized != null && underutilized;
    }

    /**
     * Check if facility has persistent underutilization (> 7 consecutive days).
     *
     * @return true if underutilized for > 7 consecutive days
     */
    public boolean hasPersistentUnderutilization() {
        return consecutiveUnderutilizedDays != null && consecutiveUnderutilizedDays > 7;
    }
}
